# Generated by Django 3.1.7 on 2021-02-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LighthouseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=512)),
                ('keyword', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=1024)),
                ('type', models.CharField(max_length=7)),
                ('position', models.IntegerField()),
                ('first_cp', models.FloatField(null=True)),
                ('lcp_score', models.FloatField(default=0, null=True)),
                ('fid_score', models.FloatField(default=0, null=True)),
                ('cls_score', models.FloatField(default=0, null=True)),
                ('largest_cp', models.FloatField(null=True)),
                ('first_mp', models.FloatField(null=True)),
                ('speed_index', models.FloatField(null=True)),
                ('estimated_il', models.FloatField(null=True)),
                ('total_blocking_time', models.FloatField(null=True)),
                ('max_potential_fid', models.FloatField(null=True)),
                ('cumulative_ls', models.FloatField(null=True)),
                ('server_response_time', models.FloatField(null=True)),
                ('first_cpu_idle', models.FloatField(null=True)),
                ('interactive', models.FloatField(null=True)),
                ('redirects', models.FloatField(null=True)),
                ('mainthread_work_breakdown', models.FloatField(null=True)),
                ('bootup_time', models.FloatField(null=True)),
                ('uses_rel_preload', models.FloatField(null=True)),
                ('network_rtt', models.FloatField(null=True)),
                ('network_sl', models.FloatField(null=True)),
                ('content_type', models.CharField(max_length=5)),
                ('largest_cp_element', models.CharField(default=None, max_length=8192, null=True)),
                ('long_cache_ttl', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lighthouse Report',
                'unique_together': {('domain', 'keyword', 'url')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=512)),
                ('country_code', models.CharField(default='us', max_length=4)),
                ('keywords_amount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lighthouse Weekly Domain',
            },
        ),
        migrations.CreateModel(
            name='LighthouseReportUnusedCSSRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=8192, null=True)),
                ('totalBytes', models.FloatField()),
                ('wastedBytes', models.FloatField()),
                ('wastedPercent', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alighthouse.lighthousereport')),
            ],
            options={
                'verbose_name': 'Lighthouse Report Unused CSS Element',
            },
        ),
        migrations.CreateModel(
            name='LighthouseReportUnminifiedJS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=8192, null=True)),
                ('totalBytes', models.FloatField()),
                ('wastedBytes', models.FloatField()),
                ('wastedPercent', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alighthouse.lighthousereport')),
            ],
            options={
                'verbose_name': 'Lighthouse Report Unminified JS Element',
            },
        ),
        migrations.CreateModel(
            name='LighthouseReportUnminifiedCSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=8192, null=True)),
                ('totalBytes', models.FloatField()),
                ('wastedBytes', models.FloatField()),
                ('wastedPercent', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alighthouse.lighthousereport')),
            ],
            options={
                'verbose_name': 'Lighthouse Report Unminified CSS Element',
            },
        ),
        migrations.CreateModel(
            name='LighthouseReportOffscreenImagesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=8192)),
                ('requestStartTime', models.FloatField(null=True)),
                ('wastedPercent', models.FloatField(null=True)),
                ('totalBytes', models.FloatField(null=True)),
                ('wastedBytes', models.FloatField(null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alighthouse.lighthousereport')),
            ],
            options={
                'verbose_name': 'Lighthouse Report Offscreen Images Item',
            },
        ),
        migrations.CreateModel(
            name='LighthouseReportNetworkSLItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=2048)),
                ('serverResponseTime', models.FloatField(null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alighthouse.lighthousereport')),
            ],
            options={
                'verbose_name': 'Lighthouse Report Network Rtt Item',
            },
        ),
        migrations.CreateModel(
            name='LighthouseReportNetworkRttItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=2048, null=True)),
                ('rtt', models.FloatField(null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alighthouse.lighthousereport')),
            ],
            options={
                'verbose_name': 'Lighthouse Report Network Rtt Item',
            },
        ),
        migrations.CreateModel(
            name='LighthouseReportNetworkReqItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=8192)),
                ('startTime', models.FloatField(null=True)),
                ('endTime', models.FloatField(null=True)),
                ('finished', models.BooleanField(default=False, null=True)),
                ('statusCode', models.IntegerField(null=True)),
                ('transferSize', models.IntegerField(null=True)),
                ('resourceSize', models.IntegerField(null=True)),
                ('mimeType', models.CharField(max_length=128, null=True)),
                ('resourceType', models.CharField(max_length=1024, null=True)),
                ('protocol', models.CharField(max_length=1024, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alighthouse.lighthousereport')),
            ],
            options={
                'verbose_name': 'Lighthouse Report Network Req Item',
            },
        ),
        migrations.CreateModel(
            name='LighthouseReportLongTaskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=8192)),
                ('startTime', models.FloatField(null=True)),
                ('duration', models.FloatField(null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alighthouse.lighthousereport')),
            ],
            options={
                'verbose_name': 'Lighthouse Report Long Task Item',
            },
        ),
        migrations.CreateModel(
            name='LighthouseReportLayoutElementsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, null=True)),
                ('path', models.CharField(max_length=8192, null=True)),
                ('selector', models.CharField(max_length=8192, null=True)),
                ('nodeLabel', models.CharField(max_length=8192, null=True)),
                ('snippet', models.CharField(max_length=8192, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alighthouse.lighthousereport')),
            ],
            options={
                'verbose_name': 'Lighthouse Report Layout Elements Item',
            },
        ),
        migrations.CreateModel(
            name='LighthouseReportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.IntegerField()),
                ('timestamp', models.CharField(max_length=512)),
                ('content_type', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=8192)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alighthouse.lighthousereport')),
            ],
            options={
                'verbose_name': 'Lighthouse Report Item',
            },
        ),
        migrations.CreateModel(
            name='LighthouseReportDiagnosticsItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numRequests', models.IntegerField()),
                ('numScripts', models.IntegerField()),
                ('numStylesheets', models.IntegerField()),
                ('numFonts', models.IntegerField()),
                ('numTasks', models.IntegerField()),
                ('numTasksOver10ms', models.IntegerField()),
                ('numTasksOver25ms', models.IntegerField()),
                ('numTasksOver50ms', models.IntegerField()),
                ('numTasksOver100ms', models.IntegerField()),
                ('numTasksOver500ms', models.IntegerField()),
                ('rtt', models.FloatField()),
                ('throughput', models.FloatField()),
                ('maxRtt', models.FloatField()),
                ('maxServerLatency', models.FloatField()),
                ('totalByteWeight', models.FloatField()),
                ('totalTaskTime', models.FloatField()),
                ('mainDocumentTransferSize', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alighthouse.lighthousereport')),
            ],
            options={
                'verbose_name': 'Lighthouse Report Diagnostics Item',
            },
        ),
        migrations.CreateModel(
            name='LighthouseReportBootupItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=8192)),
                ('total', models.FloatField()),
                ('scripting', models.FloatField()),
                ('scriptParseCompile', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alighthouse.lighthousereport')),
            ],
            options={
                'verbose_name': 'Lighthouse Report Bootup Item',
            },
        ),
    ]
