# Generated by Django 3.1.7 on 2021-04-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alighthouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lighthousereport',
            name='cls_field',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lighthousereport',
            name='fid_field',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lighthousereport',
            name='lcp_field',
            field=models.FloatField(null=True),
        ),
    ]
