# Generated by Django 3.1.7 on 2021-04-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alighthouse', '0002_auto_20210402_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighthousereportitem',
            name='data',
            field=models.CharField(max_length=16384),
        ),
    ]
