# Generated by Django 3.1.7 on 2021-04-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alighthouse', '0003_auto_20210406_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighthousereportitem',
            name='data',
            field=models.CharField(max_length=32768),
        ),
    ]
