# Generated by Django 3.1.7 on 2021-04-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alighthouse', '0004_auto_20210406_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='lighthousereportlayoutelementsitem',
            name='lhId',
            field=models.CharField(max_length=8192, null=True),
        ),
    ]
