# Generated by Django 3.1.7 on 2021-04-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alighthouse', '0005_lighthousereportlayoutelementsitem_lhid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighthousereport',
            name='largest_cp_element',
            field=models.CharField(default=None, max_length=65533, null=True),
        ),
        migrations.AlterField(
            model_name='lighthousereportitem',
            name='data',
            field=models.CharField(max_length=65533),
        ),
        migrations.AlterField(
            model_name='lighthousereportlayoutelementsitem',
            name='lhId',
            field=models.CharField(max_length=65533, null=True),
        ),
        migrations.AlterField(
            model_name='lighthousereportlayoutelementsitem',
            name='nodeLabel',
            field=models.CharField(max_length=65533, null=True),
        ),
        migrations.AlterField(
            model_name='lighthousereportlayoutelementsitem',
            name='path',
            field=models.CharField(max_length=65533, null=True),
        ),
        migrations.AlterField(
            model_name='lighthousereportlayoutelementsitem',
            name='selector',
            field=models.CharField(max_length=65533, null=True),
        ),
        migrations.AlterField(
            model_name='lighthousereportlayoutelementsitem',
            name='snippet',
            field=models.CharField(max_length=65533, null=True),
        ),
        migrations.AlterField(
            model_name='lighthousereportnetworkrttitems',
            name='origin',
            field=models.CharField(max_length=65533, null=True),
        ),
    ]
